import React from 'react'
import Popular from '../pages/home/components/Popular'
import Script from 'next/script'
// import Trending from './components/Trending'

export default function Home() {
  return (
    <>
      <Script src="https://kit.fontawesome.com/79a0c42440.js" crossorigin="anonymous" strategy='lazyOnload' />
    <Popular />
    </>
  )
}




/**<Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */